//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kalitte.Sensors.Web.UI.Pages.Shared {
    
    
    public partial class login {
        
        /// <summary>
        /// ctlLoginForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTFormPanel ctlLoginForm;
        
        /// <summary>
        /// ctlLoginHelp control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Label ctlLoginHelp;
        
        /// <summary>
        /// ctlUsername control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTTextField ctlUsername;
        
        /// <summary>
        /// ctlPassword control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTTextField ctlPassword;
        
        /// <summary>
        /// ctlRemember control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTCheckBox ctlRemember;
        
        /// <summary>
        /// TTFieldSet1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTFieldSet TTFieldSet1;
        
        /// <summary>
        /// ctlHost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTTextField ctlHost;
        
        /// <summary>
        /// ctlPort control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTNumberField ctlPort;
        
        /// <summary>
        /// ctlLoginButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTButton ctlLoginButton;
    }
}
