using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ext.Net;

using Ext.Net.Utilities;
using Kalitte.Sensors.Web.Security;
using Kalitte.Sensors.Web.UI;
using Kalitte.Sensors.Web.Core;
using System.Web.UI;

namespace Kalitte.Sensors.Web.Controls
{
    public class GridRowCommandEventArgs : EventArgs
    {
        public string ID { get; private set; }
        public int RowIndex { get; private set; }
        public string Command { get; private set; }
        public DirectEventArgs E { get; private set; }

        internal GridRowCommandEventArgs(DirectEventArgs e)
        {
            ID = e.ExtraParams["id"];
            RowIndex = int.Parse(e.ExtraParams["rowIndex"]);
            Command = e.ExtraParams["command"];
            E = e;
        }
    }

    public delegate void GridRowCommandHandler(object sender, GridRowCommandEventArgs e);

    public class TTGrid : GridPanel
    {
        public string KnownCommandPrefix { get; set; }
        public bool IsEditable { get; set; }
        public bool AutoGenerateStateCommands { get; set; }
        public bool AutoGenerateDeleteCommand { get; set; }
        public string StartItemCommandName { get; set; }
        public string StopItemCommandName { get; set; }

        private ICommandHandler mvcControl = null;
        private ICommandSource commandSource = null;

        public void SelectRow(int index)
        {
            if (RowSelection != null)
            {
                RowSelection.ClearSelections();
                RowSelection.SelectedRows.Add(new SelectedRow(index));
                RowSelection.UpdateSelection();
                //RowSelection.FireEvent("rowselect", string.Format("Ext.getCmp('{0}'", this.ClientID), index);
            }
        }

       

        public event GridRowCommandHandler GridRowCommand;

        public TTGrid()
            : base()
        {
            StripeRows = true;
            LoadMask.ShowMask = true;
            AutoGenerateStateCommands = true;
            AutoGenerateDeleteCommand = false;
            StartItemCommandName = KnownCommand.StartItem.ToString();
            StopItemCommandName = KnownCommand.StopItem.ToString();
        }

        public CheckboxSelectionModel CheckBoxSelection
        {
            get
            {
                return SelectionModel.Primary as CheckboxSelectionModel;
            }
        }

        public RowSelectionModel RowSelection
        {
            get
            {
                return SelectionModel.Primary as RowSelectionModel;
            }
        }

        protected ICommandHandler MvcControl
        {
            get
            {
                if (mvcControl == null)
                    mvcControl = GetCommandHandler(true);
                return mvcControl;
            }
        }

        protected ICommandSource CommandSource
        {
            get
            {
                if (commandSource == null)
                    commandSource = GetCommandSource();
                return commandSource;
            }
        }

        protected ICommandHandler GetCommandHandler(bool useThis)
        {
            if (useThis && this is ICommandHandler)
            {
                return (ICommandHandler)this;
            }
            else
            {
                Control t = this;
                while ((t = t.Parent) != null)
                {
                    if (t is ICommandHandler)
                    {
                        return (ICommandHandler)t;

                    }
                }
            }
            return null;
        }

        protected ICommandSource GetCommandSource()
        {

            Control t = this;
            while ((t = t.Parent) != null)
            {
                if (t is ICommandSource)
                {
                    return (ICommandSource)t;

                }
            }

            return null;
        }


        protected override void OnInit(EventArgs e)
        {
            base.OnInit(e);
            if (AutoGenerateStateCommands && !Ext.Net.X.IsAjaxRequest)
            {
                (Page as BasePage).ResMan.RegisterIcon(Ext.Net.Icon.StopBlue);
                TTCommandColumn cmdCol = new TTCommandColumn();

                StartStopGridCommand c = new StartStopGridCommand(StartItemCommandName);

                cmdCol.Commands.Add(c);

                cmdCol.PrepareToolbar.Fn = "prepareGridCommand";

                ColumnModel.Columns.Insert(0, cmdCol);
                cmdCol.Width = new System.Web.UI.WebControls.Unit(cmdCol.Commands.Count * 10);

                this.CustomConfig.Add(new ConfigItem("startItemCommandName", "'" + StartItemCommandName + "'"));
                this.CustomConfig.Add(new ConfigItem("stopItemCommandName", "'" + StopItemCommandName + "'"));

            }
            DirectEvents.Command.ExtraParams.Add(new Parameter("command", "command", ParameterMode.Raw));
            DirectEvents.Command.ExtraParams.Add(new Parameter("id", "record.id", ParameterMode.Raw));
            DirectEvents.Command.ExtraParams.Add(new Parameter("rowIndex", "rowIndex", ParameterMode.Raw));
            DirectEvents.Command.EventMask.ShowMask = true;
            DirectEvents.Command.EventMask.Target = MaskTarget.Parent;
            DirectEvents.Command.EventMask.Msg = "Processing ...";
            Listeners.Command.Handler = "return GridCommandHandler(command,record,this);";
            Listeners.RowDblClick.Fn = "gridRowDblClick";

            //this.Listeners.ViewReady.Handler = "this.getSelectionModel().selectRow(0);  this.getView().focusRow(0);";

            if (!Ext.Net.X.IsAjaxRequest)
            {
                var ttcommandcols = ColumnModel.Columns.Where(p => p is TTCommandColumn).ToList();
                foreach (TTCommandColumn item in ttcommandcols)
                {
                    if (item.MergeColumnIndex != -1)
                    {
                        if (ColumnModel.Columns[item.MergeColumnIndex] is TTCommandColumn)
                        {
                            TTCommandColumn col = (TTCommandColumn)ColumnModel.Columns[item.MergeColumnIndex];
                            col.Commands.AddRange(item.Commands);
                            ColumnModel.Columns.Remove(item);
                            col.Width = new System.Web.UI.WebControls.Unit(col.Commands.Count * 10);
                        }
                    }
                }
            }
            DirectEvents.Command.Event += new ComponentDirectEvent.DirectEventHandler(Command_Event);
            foreach (TTCmdButon btn in ControlUtils.FindControls<TTCmdButon>(this))
                btn.ConnectedGrid = this.ID;
        }



        void Command_Event(object sender, DirectEventArgs e)
        {
            var args = new GridRowCommandEventArgs(e);
            CommandInfo cmd = new CommandInfo(args.Command, e);
            cmd.Source = CommandSource;
            if (GridRowCommand != null)
                GridRowCommand(this, args);
            else if (MvcControl != null)
                MvcControl.ProcessCommand(sender, cmd);


        }



        public void SelectIfNotSelected(int index)
        {
            if (RowSelection != null && RowSelection.SelectedRows.Count == 0)
                SelectRow(index);
        }
    }
}
