//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kalitte.Sensors.Web.UI.Pages.Processors {
    
    
    public partial class ModuleEditor {
        
        /// <summary>
        /// dsStartup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTEnumStore dsStartup;
        
        /// <summary>
        /// dsNonExistEventHandler control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTEnumStore dsNonExistEventHandler;
        
        /// <summary>
        /// dsNullEventBehavior control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTEnumStore dsNullEventBehavior;
        
        /// <summary>
        /// entityWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTWindow entityWindow;
        
        /// <summary>
        /// ctlTabs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTTabPanel ctlTabs;
        
        /// <summary>
        /// ctlGenForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTFormPanel ctlGenForm;
        
        /// <summary>
        /// ctlProcessorName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Label ctlProcessorName;
        
        /// <summary>
        /// ctlModuleName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Label ctlModuleName;
        
        /// <summary>
        /// ctlDescription control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTTextField ctlDescription;
        
        /// <summary>
        /// TTFieldSet2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTFieldSet TTFieldSet2;
        
        /// <summary>
        /// TTCompositeField1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTCompositeField TTCompositeField1;
        
        /// <summary>
        /// ctlInitialStartup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTEnumCombo ctlInitialStartup;
        
        /// <summary>
        /// ctlLastException control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTExceptionViewer ctlLastException;
        
        /// <summary>
        /// ctlEventPipeGroup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTFieldSet ctlEventPipeGroup;
        
        /// <summary>
        /// ctlInheritNonExistBehaviour control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTCheckBox ctlInheritNonExistBehaviour;
        
        /// <summary>
        /// ctlNonExistEventHandler control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTEnumCombo ctlNonExistEventHandler;
        
        /// <summary>
        /// ctlInheritNullEvent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTCheckBox ctlInheritNullEvent;
        
        /// <summary>
        /// ctlNullSensorEvent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTEnumCombo ctlNullSensorEvent;
        
        /// <summary>
        /// ctlProfilePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTPanel ctlProfilePanel;
        
        /// <summary>
        /// ctlProfileEditor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.PropertyProfileEditor ctlProfileEditor;
        
        /// <summary>
        /// ctlExtendedProfilePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTPanel ctlExtendedProfilePanel;
        
        /// <summary>
        /// ctlExtendedProfileEditor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.PropertyProfileEditor ctlExtendedProfileEditor;
        
        /// <summary>
        /// ctlAnalysisPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTPanel ctlAnalysisPanel;
        
        /// <summary>
        /// ctlAnalyseItem2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.UI.Controls.Site.ItemWatchControl ctlAnalyseItem2;
        
        /// <summary>
        /// ctlSave control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTCmdButon ctlSave;
        
        /// <summary>
        /// TTButton1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTButton TTButton1;
    }
}
