//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kalitte.Sensors.Web.UI.Controls.Site {
    
    
    public partial class ServerWatchParameters {
        
        /// <summary>
        /// dsWatch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTStore dsWatch;
        
        /// <summary>
        /// dsCategory control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTStore dsCategory;
        
        /// <summary>
        /// dsInstance control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTStore dsInstance;
        
        /// <summary>
        /// dsMeasure control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTStore dsMeasure;
        
        /// <summary>
        /// ctlSourcePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTPanel ctlSourcePanel;
        
        /// <summary>
        /// ctlLocForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTFormPanel ctlLocForm;
        
        /// <summary>
        /// Container1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTContainer Container1;
        
        /// <summary>
        /// ctlLogSourceForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTFormPanel ctlLogSourceForm;
        
        /// <summary>
        /// ctlProviders control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTComboBox ctlProviders;
        
        /// <summary>
        /// ctlCategoryForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTFormPanel ctlCategoryForm;
        
        /// <summary>
        /// ctlCategory control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTComboBox ctlCategory;
        
        /// <summary>
        /// TTFormPanel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTFormPanel TTFormPanel1;
        
        /// <summary>
        /// TTContainer1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTContainer TTContainer1;
        
        /// <summary>
        /// ctlSelectLogSourceForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTFormPanel ctlSelectLogSourceForm;
        
        /// <summary>
        /// ctlInstance control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTComboBox ctlInstance;
        
        /// <summary>
        /// TTFormPanel2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTFormPanel TTFormPanel2;
        
        /// <summary>
        /// ctlMeasure control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.Sensors.Web.Controls.TTComboBox ctlMeasure;
    }
}
